GOOGLE_CLIENT_ID = ENV['GOOGLE_CLIENT_ID']
GOOGLE_CLIENT_SECRET = ENV['GOOGLE_CLIENT_ID']
GOOGLE_REDIRECT_URI = ENV['GOOGLE_REDIRECT_URI'] # Adjust as needed
GOOGLE_AUTH_URL = ENV['GOOGLE_AUTH_URL']
GOOGLE_TOKEN_URL = ENV['GOOGLE_TOKEN_URL']
